// <auto-generated />
namespace AnimaniaConsole.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MakeUserNameSmallerFrom6To4Chars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeUserNameSmallerFrom6To4Chars));
        
        string IMigrationMetadata.Id
        {
            get { return "201803241213405_MakeUserNameSmallerFrom6To4Chars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
