// <auto-generated />
namespace AnimaniaConsole.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class YesYesYes_DataSeedWorks_Now_Add_back_The_Images_Data_In_Post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YesYesYes_DataSeedWorks_Now_Add_back_The_Images_Data_In_Post));
        
        string IMigrationMetadata.Id
        {
            get { return "201803180959470_YesYesYes_DataSeedWorks_Now_Add_back_The_Images_Data_In_Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
