// <auto-generated />
namespace AnimaniaConsole.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class someunknownpendingchangesasaresultofassemblyerrorwithAnimaniaConsoleModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(someunknownpendingchangesasaresultofassemblyerrorwithAnimaniaConsoleModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803151613347_some unknown pending changes as a result of assembly error with AnimaniaConsole.Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
